//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MV_P1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        public int No_emp { get; set; }
        public string nombre { get; set; }
        public string seriePC { get; set; }
        public string puesto { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual Maquina Maquina { get; set; }
    }
}
