//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MV_P1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maquina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Maquina()
        {
            this.contras = new HashSet<contra>();
            this.empleadoes = new HashSet<empleado>();
            this.Tiendas = new HashSet<Tienda>();
        }
    
        public int Conteo { get; set; }
        public string Contratos { get; set; }
        public string Producto { get; set; }
        public string Descripcion { get; set; }
        public string SeriePC { get; set; }
        public string Destino { get; set; }
        public string Asignada { get; set; }
        public string Estatuss { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string NombreUsuarioPuesto { get; set; }
        public string NoCartaCustodia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contra> contras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<empleado> empleadoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tienda> Tiendas { get; set; }
    }
}
