//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MV_P1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tienda
    {
        public int ID_Tienda { get; set; }
        public string DeptoTienda { get; set; }
        public Nullable<int> NoTienda { get; set; }
        public string NombreTienda { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string DireccionTienda { get; set; }
        public string SeriePC { get; set; }
    
        public virtual Maquina Maquina { get; set; }
    }
}
