//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MV_P1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tiendas
    {
        public int ID_Tienda { get; set; }
        public string DeptoTienda { get; set; }
        public int NoTienda { get; set; }
        public string NombreTienda { get; set; }
        public string DireccionTienda { get; set; }
        public string SeriePC { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual Maquinas Maquinas { get; set; }
    }
}
